name: CI/CD
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        type: string
        required: true
jobs:
  call_main_workflow:
    uses: kmhalpin/workflows/.github/workflows/main.yml@main
    with:
      project_name: 'forum-api'
      project_environment: 'production'
      project_language: 'nodejs'
      project_language_version: '18.x'
      test_services: '["postgres"]'
      e2e_test_type: 'newman'
      postman_collection_path: '.github/postman/collections/Forum API V2 Test.json'
      postman_environment_path: '.github/postman/environments/Forum API V2 Test.json'
      docker_image_name: 'kmhalpin/forum-api'
      docker_image_tag: ${{ inputs.docker_image_tag }}
      dockerhub_username: 'kmhalpin'
      aws_ecs_task_definition_file_path: '.github/aws/ecs_task.json'
      aws_ecs_task_definition_container_name: 'forum-api'
      aws_ecs_service_name: 'forum-api'